"""Application-wide constants that are safe to import without wxPython."""

DEFAULT_COM_PORT = "COM3"
DEFAULT_BAUDRATE = 38400
DEFAULT_COMPLIANCE_V = 5.0
DEFAULT_INTERNAL_MAX_CURRENT_MA = 110.0
DEFAULT_CALIBRATION_FILENAME = "default_intensity_calibration.csv"
DEFAULT_CALIBRATION_FIT_X_MIN_MA = "67"
DEFAULT_CALIBRATION_FIT_X_MAX_MA = "94"
DEFAULT_FUNCTION_EXPR = "x*m+b"
DEFAULT_FUNCTION_X_MIN = "0"
DEFAULT_FUNCTION_X_MAX = "180"
DEFAULT_FUNCTION_Y_MIN = "0.1"
DEFAULT_FUNCTION_Y_MAX = "4.99"
SERIAL_TIMEOUT_S = 5.0
QUICK_TEST_PREVIEW_TIME_S = 10.0
FUNCTION_PROFILE_POINTS = 300
FUNCTION_EXEC_MIN_INTERVAL_S = 0.05


